version: '2'
services:
    poc-app:
        image: poc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=poc-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    poc-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: poc-cassandra
    poc-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=poc-cassandra
    poc-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: poc-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
